# Generated by Django 3.0.3 on 2020-03-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='pages',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='song',
        ),
    ]
